### ISSUE TITLE
[Bug] 'team' table seems to be optional

### ISSUE THREAD

**Issue by paulavidela** [fivetran/dbt_github_source#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

We use a Fivetran connector for Github and we sync all available tables (including `team` and `team_membership`. However, we are not using that feature in Github, so those tables are not materialized in our DW. Therefore, running all github models failed. 

Following the [readme](https://github.com/fivetran/dbt_github_source#step-4-disable-models-for-non-existent-sources) for `REPO_TEAM`, we tried adding `{{ config(enabled=var('github__using_team', True)) }}` to `stg_github__team` and `stg_github__team_tmp` and editing the `dbt_project.yml`: that worked! 

### Relevant error log or model output

```shell
Runtime Error in model stg_github__team_tmp (models/tmp/stg_github__team_tmp.sql)
404 Not found
```

### Expected behavior

To run all models without errors by setting a new variable

### dbt Project configurations

```
config-version: 2

name: 'github_source'
version: '0.5.0'

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  github_source:
    materialized: table
    tmp:
      materialized: view

vars:
  github_source:
    issue_assignee: "{{ source('github', 'issue_assignee') }}"
    issue_closed_history: "{{ source('github', 'issue_closed_history') }}"
    issue_comment: "{{ source('github', 'issue_comment') }}"
    issue_label: "{{ source('github', 'issue_label') }}"
    label: "{{ source('github', 'label') }}"
    issue_merged: "{{ source('github', 'issue_merged') }}"
    issue: "{{ source('github', 'issue') }}"
    pull_request_review: "{{ source('github', 'pull_request_review') }}"
    pull_request: "{{ source('github', 'pull_request') }}"
    repo_team: "{{ source('github', 'repo_team') }}"
    repository: "{{ source('github', 'repository') }}"
    requested_reviewer_history: "{{ source('github', 'requested_reviewer_history') }}"
    team: "{{ source('github', 'team') }}"
    user: "{{ source('github', 'user') }}"
    
    github__using_repo_team: false # by default this is assumed to be true
```

### Package versions

```
  - package: fivetran/github
    version: [">=0.5.0", "<0.6.0"]
    
```
    (we checked the new release before opening this issue)

### What database are you using dbt with?

bigquery

### dbt Version

```
Core:
  - installed: 1.3.1
  - latest:    1.3.2 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.3.0 - Up to date!
```

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
