### ISSUE TITLE
Freshness Override

### ISSUE THREAD

**Issue by raphaelvarieras** [fivetran/dbt_github_source#35]
I am getting a freshness error with this package:

`15:09:53  25 of 98 ERROR STALE freshness of github.repo_team ............................. [ERROR STALE in 0.74s]`

As a result I am trying to override it with a YAML configuration but I can't figure out how to do it exactly. Shouldn't this work?

```
version: 2

sources:
  - name: github_source_override
    database: my_db
    schema: github
    overrides: github_source

    tables:
    - name: repo_team
      freshness:
```

**Comment by fivetran-joemarkiewicz** [comment]
Hey @raphaelvarieras that does look correct. The only other option I would attempt is renaming the `name` to be the same one we use in the GitHub Source package (`github`). Could you try the following and see if it works.

```yml
## your own src.yml in your root directory
version: 2

sources:
  - name: github
    database: my_db
    schema: github
    overrides: github_source

    tables:
    - name: repo_team
      freshness:
```
